name: point_of_sales_flutter
description: "Point of Sale Application with Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  
  # Network
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # UI & Fonts
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # Utils
  intl: ^0.19.0
  
  # Icons
  cupertino_icons: ^1.0.6
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Uncomment jika mau tambah assets
  # assets:
  #   - assets/images/
  #   - assets/icons/